### ISSUE TITLE
Build the Email Template Creator

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#11]
Description:
Develop a feature that enables users to create and save reusable email templates with dynamic placeholders for personalization (e.g., recipient name, company name).

Tasks:

Design a frontend interface for creating email templates:
Provide an HTML editor or a drag-and-drop interface.
Allow users to add placeholders like {{RecipientName}}, {{CompanyName}}.
Create a backend endpoint (POST /api/templates) to save templates to the database.
Fetch existing templates with another endpoint (GET /api/templates).
Provide preview functionality for templates to visualize the email content with placeholders.
Add validation to ensure that templates are not saved with invalid HTML or broken placeholders.

Estimated Time: 48 hours

Please claim this issue

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
@PriyamJChakrabarty we can only assign you 3 issues at max
