### ISSUE TITLE
Schedule Automated Email Dispatch

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#12]
Description:
Develop backend logic to allow users to schedule automated email campaigns to be sent at specific times.

Tasks:

Update the database schema to include a scheduled_time field for campaigns.
Use a job scheduler library like node-schedule or Agenda.js to queue and send emails at the specified time.
Create an endpoint (POST /api/campaigns/schedule) to schedule emails:
Include required fields like campaign name, template ID, recipient list, and schedule time.
Send emails using a service like Nodemailer or an external provider (e.g., SendGrid, Amazon SES).
Ensure proper logging of email status (e.g., sent, failed) for tracking purposes.
Handle errors gracefully and retry sending failed emails up to a configurable limit.

Estimated Time: 60 hours

Please claim this issue

**Comment by ayush-patel1** [comment]
claim
