### ISSUE TITLE
Design the Database Schema for SponsoHive

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#2]
Create a well-structured database schema to manage users, email lists, campaigns, and templates efficiently.

Tasks:

Define models:
User: Name, email, hashed password, roles (e.g., Admin, Team Member).
EmailList: Name, tags, contacts (email, name, etc.).
Campaign: Name, email list ID, schedule, and status.
Template: Title, content, placeholders (e.g., {name}, {company}).
Establish relationships:
Link campaigns to email lists and users.
Ensure proper indexing for faster query execution.
Write initial seed data to populate the database for testing.
Document the schema structure for contributors.

Estimated Time: 72 hours

Note:Please claim this issue

**Comment by Sarvesh0955** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by ANJALIJAISWAL4213** [comment]
@Sarvesh0955 tell me what's the progress and share your discord username
