### ISSUE TITLE
Set Up Follow-Up Email Sequences

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#25]
### Description:   
Automate follow-up email sequences for recipients who don’t respond within a specified timeframe.    
### Tasks:  
1. Add a follow_up field to campaigns in the database to define follow-up intervals (e.g., 3 days after no response).
2. Develop backend logic to track email responses and trigger follow-ups for non-responders.
3. Create an endpoint (PATCH /api/campaigns/follow-up) to update follow-up settings.
4. Test the system thoroughly to ensure follow-ups are sent only to non-responders and respect user-defined intervals.

**Comment by official-ashutosh** [comment]
claim

**Comment by Vardaan-02** [comment]
i have unassigned myself because i will not be able to solve this issue

Please assign someone more skilled than me

**Comment by Vardaan-02** [comment]
sorry for the inconvenience

**Comment by official-ashutosh** [comment]
Claim
