### ISSUE TITLE
Develop User Authentication for SponsoHive

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#3]
Develop a secure and efficient user authentication system to allow users to register, log in, and access the platform while protecting sensitive data.

Tasks:

Design signup and login routes in the backend API.
Implement password hashing using bcrypt.
Generate JWTs (JSON Web Tokens) for session management and secure user authentication.
Create middleware to protect private routes using JWT.
Add email verification to activate accounts upon registration.
Thoroughly test the authentication system using unit and integration tests.

Estimated Time: 72 hours

Note:Please claim this issue

**Comment by ayush-patel1** [comment]
claim

**Comment by anubhabnath098** [comment]
@Ishu0112 share updates on your task

**Comment by Ishu0112** [comment]
@anubhabnath098 i am working on it like i have made the functions the email verification is left and some basic connection between these. Will try to complete it by today
