### ISSUE TITLE
Add File Attachments to Campaign Emails

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#31]
### Description:
Allow users to attach relevant documents (e.g., sponsorship proposals, event brochures) to their email campaigns.

### Tasks:
1. Limit file types to common document formats (e.g., PDF, DOCX) and enforce a maximum file size (e.g., 5MB).
2. Store uploaded files securely in cloud storage (e.g., AWS S3, Firebase, Cloudinary).
3. Modify the email dispatch logic to include attachments while sending emails.
4. Add error handling for scenarios like invalid file types or failed uploads.
5. Test the feature by attaching various file types and sizes to ensure reliability.

Edit: Use Cloudinary Storage since it is free and does not have any complicated billing set up. But make sure you update the readme. We wont merge your pull request until the readme has proper instruction regarding setting up cloudinary storage and environment variables and api keys

**Comment by ayush-patel1** [comment]
claim

**Comment by ayush-patel1** [comment]
claim
