### ISSUE TITLE
Document the Campaign Automation Feature

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#32]
### Description:
Write detailed documentation to guide contributors and users on the implementation and usage of the email campaign automation feature.

### Tasks:
1. Create a README section explaining the feature’s functionality.
2. Provide API documentation for campaign-related endpoints:
3. Template creation and management.
4. Scheduling and follow-ups.
5. Fetching campaign stats.
6. Include step-by-step instructions for setting up email services (e.g., SendGrid, Amazon SES).
7. Add a contributor’s guide with coding standards and setup instructions for this feature.
8. Use examples and screenshots to make the documentation user-friendly.

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by oopshwet** [comment]
claim
