### ISSUE TITLE
Implement Open Rate Tracking for Email Campaigns

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#38]
### Tasks:
Generate Unique URL for Tracking Pixel: (all the requests should take place in /api/analytics/....)

1. For each email sent, generate a unique tracking URL that will be embedded as an invisible tracking pixel in the email body.
2. The URL should include query parameters to identify the recipient and the campaign, such as:  
i. recipientId=<recipient_id>
ii. campaignId=<campaign_id>
3. Store the generated URL in the database along with the recipient and campaign information.

### In the front end this will happen
Embed Tracking Pixel in the Email:

Embed the unique tracking URL into the email HTML as an invisible 1x1 pixel image:
html
### Handle the Request for Tracking:

4. When the email is opened, the recipient's email client will request the tracking pixel URL.
5. Set up a backend route (e.g., /track) to handle incoming requests to the tracking pixel.
6. Capture the recipientId and campaignId from the query parameters and log the event (record the open).
### For each email open, store the following data in the database:
7. Campaign ID: Identifies the campaign the email belongs to.
8. Recipient ID: Identifies the recipient who opened the email.
9. Timestamp: The time when the email was opened.

### Estimated Time : 72 hours

**Comment by ayush-patel1** [comment]
claim
