### ISSUE TITLE
Develop Role-Based Access Control (RBAC) Description:

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#4]
Implement role-based access control to ensure users can only access features permitted by their roles.

Tasks:

Define roles in the system (Admin, Manager, Contributor).
Write middleware to verify user roles before granting access to routes.
Restrict sensitive operations (e.g., campaign edits) to specific roles.
Add a role field in the User model and seed test users with various roles.
Document how roles are assigned and used in the platform.

Estimated Time: 72 hours

Note:Please claim this issue

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by anubhabnath098** [comment]
@PriyamJChakrabarty share updates on your task

**Comment by PriyamJChakrabarty** [comment]
Hello @anubhabnath098 Almost Done

Will release a PR soon
