### ISSUE TITLE
Develop Click-Through Rate (CTR) Monitoring

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#40]
### Description:
Track how many recipients clicked on links in the email, providing insights into recipient engagement.

#### Assume that: In the frontend users will be able to insert trackable links.
1. Create a backend service to generate unique, trackable URLs for each link and recipient.
2. Log every click event to the database with:
I. Campaign ID
II. Recipient ID
III. Timestamp
IV. Target URL
3. Create an API endpoint corresponding to each link and send the (number of clicks) as a response.  
4. Create another API endpoint corresponding to each Campaign ID and send the click through rate (number of clicks/number of emails emails containing the link sent).  
5. Test the CTR functionality with emails containing multiple links.

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by kanav67** [comment]
claim

**Comment by official-ashutosh** [comment]
claim
