### ISSUE TITLE
Set Up Response Rate Tracking

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#41]
### Description:
Enable users to monitor how many recipients reply to their email campaigns. This provides a direct measure of engagement.

### Tasks:

1. Configure the email server to track replies to campaign emails using a unique "Reply-To" address for each campaign.
2. Parse incoming emails to identify replies and match them to campaigns and recipients.
3. Store reply metrics in the database:
Campaign ID
Recipient ID
Timestamp
4. Update the campaign dashboard to include response rate metrics (e.g., total replies, percentage).
5. Notify campaign owners of replies in real-time through in-app notifications.
6. Test the response tracking system with various email clients.

**Comment by ayush-patel1** [comment]
claim

**Comment by kanav67** [comment]
claim

**Comment by official-ashutosh** [comment]
Claim
