### ISSUE TITLE
Implement Dynamic Placeholders in Email Templates

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#45]
Core Feature Issues: Personalization  (so it has to be done in separate file)

Description:
Create functionality to replace placeholders in email templates (e.g., {{RecipientName}}, {{CompanyName}}) with actual data from the recipient list when sending campaigns.

Tasks:

Parse the email template content and identify placeholders.
Fetch user-specific data (e.g., name, company, position) from the database or recipient list.
Replace placeholders with corresponding data dynamically during email generation.
Ensure fallback values for missing data (e.g., "Valued Sponsor" if RecipientName is missing).
Add backend validation to check for unused or invalid placeholders in the template.
Test functionality for various cases (e.g., templates with no placeholders, missing data fields).

Estimated Time: 48 hours

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by kanav67** [comment]
@ANJALIJAISWAL4213 Snehalgupta already has another assigned issue in this repo, please assign it to me

**Comment by Snehalgupta-07** [comment]
> @ANJALIJAISWAL4213 Snehalgupta already has another assigned issue in this repo, please assign it to me

There are other repos as well in which multiple issues are assigned to a single person

**Comment by anubhabnath098** [comment]
this issue will be closed as it was already done before. Sorry for the inconvenience.
