### ISSUE TITLE
Implement Open Rate Tracking for Email Campaigns

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#46]
Core Feature Issues: Performance Analytics  (so it has to be done in new file)

Description:
Develop a mechanism to track the percentage of recipients who open emails from a campaign. This helps users evaluate the effectiveness of their email subject lines and targeting.

Tasks:

Insert an invisible tracking pixel (e.g., a 1x1 transparent image) in the email body.
Generate a unique URL for the tracking pixel for each email sent.
When the recipient opens the email, log the request to the server to record the event.
Store open events in the database with details like:
Campaign ID
Recipient ID
Timestamp
Create a frontend dashboard widget to display open rates (e.g., percentage and graph).
Test open tracking across multiple email clients (e.g., Gmail, Outlook).

Estimated Time: 72 hours

**Comment by Sanket6652** [comment]
Claim

**Comment by rajbir40** [comment]
claim

**Comment by kanav67** [comment]
claim

**Comment by anubhabnath098** [comment]
there was a mistake. This issue has already been done
