### ISSUE TITLE
Monitor Bounce Rates and Unsubscribes

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#47]
### Description:
Add functionality to monitor email bounce rates (failed delivery) and manage unsubscribes to maintain sender reputation and comply with regulations.

###Tasks:

1. Configure the email server to handle bounce notifications (both hard and soft bounces).
2. Parse bounce data and update the recipient’s status in the database (e.g., "Bounced," "Inactive").
3. Add an "Unsubscribe" link to all emails to allow recipients to opt-out.
4. Create a backend endpoint to process unsubscribe requests and update recipient preferences.
5. Display bounce and unsubscribe metrics in the dashboard.
6.Test the feature by simulating various bounce scenarios and unsubscribe actions.

You will only need to implement the backend part. Open Pull request with proper screen shot and there should be no merge conflicts

**Comment by ayush-patel1** [comment]
claim
