### ISSUE TITLE
Develop Integration with HubSpot CRM

### ISSUE THREAD

**Issue by anubhabnath098** [opencodeiiita/SponsoHive-Backend#48]
### Description:
Enable users to sync their email lists and campaign data with HubSpot CRM, providing seamless data management between platforms.

### Tasks:

1. Set up OAuth authentication to securely connect SponsoHive accounts with HubSpot.
2. Implement API endpoints to:
i) Fetch contact lists from HubSpot.
ii) Sync new contacts created in SponsoHive to HubSpot.
iii) Update contact information bidirectionally.
iv) Test the integration with various HubSpot account types and data sizes.
v) Provide error handling and clear feedback for connection issues.

**Comment by kanav67** [comment]
claim

**Comment by ayush-patel1** [comment]
claim
