### ISSUE TITLE
Develop the Bulk Upload Feature for Email Lists

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#6]
Description:Core Feature Issues: Email List Management
Create a feature that enables users to upload email lists in bulk via CSV/Excel files. The uploaded files should be processed to extract valid email data and provide feedback to the user.

Tasks:

Create a backend endpoint to handle file uploads (POST /api/email-lists/upload).
Use a library like Multer for file handling and csv-parser/xlsx for parsing CSV/Excel files.
Validate file format (only .csv and .xlsx allowed).
Parse the uploaded file and validate data:
Check for valid email format.
Identify and log any invalid rows.
Save valid emails to the database under a new or existing list.
Return a detailed response to the user, including upload status and errors (if any).
Estimated Time: 48 hours

**Comment by shubh5921** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by anubhabnath098** [comment]
@vivekanandram9 share updates on your task as well as share your discord username

**Comment by vivekanandram9** [comment]
My I pushed it now only , I was having difficulty in resolving the error I
was having with the post rout. discord: vivekanand9

**Comment by anubhabnath098** [comment]
@shubh5921 are you working on this task?

**Comment by anubhabnath098** [comment]
@shubh5921 i did not get any response from you so i am assigning this task to someone else
