### ISSUE TITLE
Implement Contact Categorization

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#7]
Description:Core Feature Issues: Email List Management
Enable users to organize and categorize contacts in email lists by assigning tags (e.g., industry, priority). Tags should be stored in the database and displayed on the frontend.

Tasks:

Update the EmailList schema to include a tags field (array of strings).
Create a backend route (PATCH /api/email-lists/:id/tags) to add or remove tags for an email list.
Design a frontend interface allowing users to:
Add new tags to a list.
View, edit, and delete existing tags.
Ensure tags are searchable and filterable for better organization.
Write API documentation for the tagging feature.

Estimated Time: 60 hours

Pleae claim this issue

**Comment by 07CalC** [comment]
claim
