### ISSUE TITLE
Add Duplicate Detection for Email Lists

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#8]
Description:
Develop a mechanism to detect and handle duplicate email addresses during uploads or manual additions.

Tasks:

Add duplicate detection logic to the bulk upload process:
Compare emails in the uploaded file with those already in the database.
Flag duplicates and exclude them from insertion.
Create an endpoint (POST /api/email-lists/check-duplicates) to check for duplicates in real-time during manual entry.
Notify users about duplicates during uploads or manual entry, with an option to overwrite or ignore.
Provide a detailed summary of duplicates in the response.
Test the duplicate detection process thoroughly.
Estimated Time: 48 hours

**Comment by anubhabnath098** [comment]
@swarupn17 share the progress on your task and also your share your discord username

**Comment by swarupn17** [comment]
Kindly unassign this task to me as i am working on other tasks.
