### ISSUE TITLE
Create Pagination for Email Lists

### ISSUE THREAD

**Issue by ANJALIJAISWAL4213** [opencodeiiita/SponsoHive-Backend#9]
Description:
Implement a pagination system on the frontend to handle large email lists efficiently.

Tasks:

Add pagination support to the backend endpoint for fetching email lists (GET /api/email-lists?page=1&limit=50).
Use query parameters (page and limit) to return paginated data from the database.
Design the frontend UI to display paginated lists with navigation controls (Next, Previous, Go to Page).
Ensure seamless navigation with loading indicators for better UX.
Document API changes and pagination usage in the README.
Estimated Time: 36 hours

**Comment by official-ashutosh** [comment]
claim
